### PR TITLE
New textures, sound

### PR DESCRIPTION
**Pull request by tacotexmex**

### CODE REVIEW

**Comment by bell07** [comment]
Looks really nice!
The License is still CC BY-SA?

**Comment by tacotexmex** [comment]
Sure! Forgot about license.

**Comment by tacotexmex** [comment]
Do I put my name on it as well?

**Comment by tacotexmex** [comment]
What the hell, committing in a sound effect as well. Added licensing to readme.

**Comment by bell07** [comment]
I tested it shorly and I like it! Are you finished? Can I merge your changes?

**Comment by tacotexmex** [comment]
Yes, finished. Licenses in order and all. Commence merge! :shipit:

**Comment by bell07** [comment]
Thanks!

**Pull request merged**
