### PR TITLE
Replace deprecated settings method

### PR DESCRIPTION
**Pull request by tacotexmex**

### CODE REVIEW

**Comment by bell07** [comment]
Thank you!

**Comment by bell07** [comment]
I removed this change from master because it does not work with current stable minetest-0.4.16.
` attempt to call method 'get_pos' (a nil value)` appears.
But I moved it to the new created "mt_development" branch and will merge if 0.4.17 is out

**Comment by tacotexmex** [comment]
Huh. That makes the new settings method even more confusing.

**Comment by bell07** [comment]
Now I got it;) The minetest.setting:get_pos(name) is not in MT-0.4.16. the get() and get_bool() are ok.
Now I merged your patch again and reverted the get_pos only.
Does the get_pos working on the latest development version? I am a stable user...

**Comment by tacotexmex** [comment]
Ah, that's good. To be honest I counted on all setting types to have been converted to the new format, I did not try it. I did ~30 "Replace deprecated settings method " PRs to various mods and I've only seen get_pos in yours, so I don't know the status of that particular settings type. Sorry 😊

**Pull request merged**
